// @ts-nocheck
import * as __fd_glob_63 from "../content/docs/components/tree.mdx?collection=docs"
import * as __fd_glob_62 from "../content/docs/components/tooltip.mdx?collection=docs"
import * as __fd_glob_61 from "../content/docs/components/toolbar.mdx?collection=docs"
import * as __fd_glob_60 from "../content/docs/components/toggle.mdx?collection=docs"
import * as __fd_glob_59 from "../content/docs/components/toggle-group.mdx?collection=docs"
import * as __fd_glob_58 from "../content/docs/components/toast.mdx?collection=docs"
import * as __fd_glob_57 from "../content/docs/components/timeline.mdx?collection=docs"
import * as __fd_glob_56 from "../content/docs/components/textarea.mdx?collection=docs"
import * as __fd_glob_55 from "../content/docs/components/tabs.mdx?collection=docs"
import * as __fd_glob_54 from "../content/docs/components/table.mdx?collection=docs"
import * as __fd_glob_53 from "../content/docs/components/switch.mdx?collection=docs"
import * as __fd_glob_52 from "../content/docs/components/slider.mdx?collection=docs"
import * as __fd_glob_51 from "../content/docs/components/skeleton.mdx?collection=docs"
import * as __fd_glob_50 from "../content/docs/components/sheet.mdx?collection=docs"
import * as __fd_glob_49 from "../content/docs/components/separator.mdx?collection=docs"
import * as __fd_glob_48 from "../content/docs/components/select.mdx?collection=docs"
import * as __fd_glob_47 from "../content/docs/components/scroll-area.mdx?collection=docs"
import * as __fd_glob_46 from "../content/docs/components/resizable.mdx?collection=docs"
import * as __fd_glob_45 from "../content/docs/components/radio-group.mdx?collection=docs"
import * as __fd_glob_44 from "../content/docs/components/progress.mdx?collection=docs"
import * as __fd_glob_43 from "../content/docs/components/preview-card.mdx?collection=docs"
import * as __fd_glob_42 from "../content/docs/components/popover.mdx?collection=docs"
import * as __fd_glob_41 from "../content/docs/components/pagination.mdx?collection=docs"
import * as __fd_glob_40 from "../content/docs/components/navigation-menu.mdx?collection=docs"
import * as __fd_glob_39 from "../content/docs/components/meter.mdx?collection=docs"
import * as __fd_glob_38 from "../content/docs/components/menubar.mdx?collection=docs"
import * as __fd_glob_37 from "../content/docs/components/kbd.mdx?collection=docs"
import * as __fd_glob_36 from "../content/docs/components/input.mdx?collection=docs"
import * as __fd_glob_35 from "../content/docs/components/input-otp.mdx?collection=docs"
import * as __fd_glob_34 from "../content/docs/components/input-group.mdx?collection=docs"
import * as __fd_glob_33 from "../content/docs/components/fancy-button.mdx?collection=docs"
import * as __fd_glob_32 from "../content/docs/components/dropdown-menu.mdx?collection=docs"
import * as __fd_glob_31 from "../content/docs/components/drawer.mdx?collection=docs"
import * as __fd_glob_30 from "../content/docs/components/dialog.mdx?collection=docs"
import * as __fd_glob_29 from "../content/docs/components/date-range-picker.mdx?collection=docs"
import * as __fd_glob_28 from "../content/docs/components/date-picker.mdx?collection=docs"
import * as __fd_glob_27 from "../content/docs/components/cropper.mdx?collection=docs"
import * as __fd_glob_26 from "../content/docs/components/copy-button.mdx?collection=docs"
import * as __fd_glob_25 from "../content/docs/components/context-menu.mdx?collection=docs"
import * as __fd_glob_24 from "../content/docs/components/command.mdx?collection=docs"
import * as __fd_glob_23 from "../content/docs/components/combobox.mdx?collection=docs"
import * as __fd_glob_22 from "../content/docs/components/collapsible.mdx?collection=docs"
import * as __fd_glob_21 from "../content/docs/components/code-block.mdx?collection=docs"
import * as __fd_glob_20 from "../content/docs/components/circular-slider.mdx?collection=docs"
import * as __fd_glob_19 from "../content/docs/components/checkbox.mdx?collection=docs"
import * as __fd_glob_18 from "../content/docs/components/checkbox-group.mdx?collection=docs"
import * as __fd_glob_17 from "../content/docs/components/carousel.mdx?collection=docs"
import * as __fd_glob_16 from "../content/docs/components/card.mdx?collection=docs"
import * as __fd_glob_15 from "../content/docs/components/calendar.mdx?collection=docs"
import * as __fd_glob_14 from "../content/docs/components/button.mdx?collection=docs"
import * as __fd_glob_13 from "../content/docs/components/button-group.mdx?collection=docs"
import * as __fd_glob_12 from "../content/docs/components/breadcrumbs.mdx?collection=docs"
import * as __fd_glob_11 from "../content/docs/components/badge.mdx?collection=docs"
import * as __fd_glob_10 from "../content/docs/components/avatar.mdx?collection=docs"
import * as __fd_glob_9 from "../content/docs/components/autocomplete.mdx?collection=docs"
import * as __fd_glob_8 from "../content/docs/components/aspect-ratio.mdx?collection=docs"
import * as __fd_glob_7 from "../content/docs/components/alert.mdx?collection=docs"
import * as __fd_glob_6 from "../content/docs/components/alert-dialog.mdx?collection=docs"
import * as __fd_glob_5 from "../content/docs/components/accordion.mdx?collection=docs"
import * as __fd_glob_4 from "../content/docs/getting-started/introduction.mdx?collection=docs"
import * as __fd_glob_3 from "../content/docs/getting-started/installation.mdx?collection=docs"
import { default as __fd_glob_2 } from "../content/docs/getting-started/meta.json?collection=docs"
import { default as __fd_glob_1 } from "../content/docs/components/meta.json?collection=docs"
import { default as __fd_glob_0 } from "../content/docs/meta.json?collection=docs"
import { server } from 'fumadocs-mdx/runtime/server';
import type * as Config from '../source.config';

const create = server<typeof Config, import("fumadocs-mdx/runtime/types").InternalTypeConfig & {
  DocData: {
  }
}>({"doc":{"passthroughs":["extractedReferences"]}});

export const docs = await create.docs("docs", "content/docs", {"meta.json": __fd_glob_0, "components/meta.json": __fd_glob_1, "getting-started/meta.json": __fd_glob_2, }, {"getting-started/installation.mdx": __fd_glob_3, "getting-started/introduction.mdx": __fd_glob_4, "components/accordion.mdx": __fd_glob_5, "components/alert-dialog.mdx": __fd_glob_6, "components/alert.mdx": __fd_glob_7, "components/aspect-ratio.mdx": __fd_glob_8, "components/autocomplete.mdx": __fd_glob_9, "components/avatar.mdx": __fd_glob_10, "components/badge.mdx": __fd_glob_11, "components/breadcrumbs.mdx": __fd_glob_12, "components/button-group.mdx": __fd_glob_13, "components/button.mdx": __fd_glob_14, "components/calendar.mdx": __fd_glob_15, "components/card.mdx": __fd_glob_16, "components/carousel.mdx": __fd_glob_17, "components/checkbox-group.mdx": __fd_glob_18, "components/checkbox.mdx": __fd_glob_19, "components/circular-slider.mdx": __fd_glob_20, "components/code-block.mdx": __fd_glob_21, "components/collapsible.mdx": __fd_glob_22, "components/combobox.mdx": __fd_glob_23, "components/command.mdx": __fd_glob_24, "components/context-menu.mdx": __fd_glob_25, "components/copy-button.mdx": __fd_glob_26, "components/cropper.mdx": __fd_glob_27, "components/date-picker.mdx": __fd_glob_28, "components/date-range-picker.mdx": __fd_glob_29, "components/dialog.mdx": __fd_glob_30, "components/drawer.mdx": __fd_glob_31, "components/dropdown-menu.mdx": __fd_glob_32, "components/fancy-button.mdx": __fd_glob_33, "components/input-group.mdx": __fd_glob_34, "components/input-otp.mdx": __fd_glob_35, "components/input.mdx": __fd_glob_36, "components/kbd.mdx": __fd_glob_37, "components/menubar.mdx": __fd_glob_38, "components/meter.mdx": __fd_glob_39, "components/navigation-menu.mdx": __fd_glob_40, "components/pagination.mdx": __fd_glob_41, "components/popover.mdx": __fd_glob_42, "components/preview-card.mdx": __fd_glob_43, "components/progress.mdx": __fd_glob_44, "components/radio-group.mdx": __fd_glob_45, "components/resizable.mdx": __fd_glob_46, "components/scroll-area.mdx": __fd_glob_47, "components/select.mdx": __fd_glob_48, "components/separator.mdx": __fd_glob_49, "components/sheet.mdx": __fd_glob_50, "components/skeleton.mdx": __fd_glob_51, "components/slider.mdx": __fd_glob_52, "components/switch.mdx": __fd_glob_53, "components/table.mdx": __fd_glob_54, "components/tabs.mdx": __fd_glob_55, "components/textarea.mdx": __fd_glob_56, "components/timeline.mdx": __fd_glob_57, "components/toast.mdx": __fd_glob_58, "components/toggle-group.mdx": __fd_glob_59, "components/toggle.mdx": __fd_glob_60, "components/toolbar.mdx": __fd_glob_61, "components/tooltip.mdx": __fd_glob_62, "components/tree.mdx": __fd_glob_63, });